name: MiniSuperApp
packages: 
 CombineExt:
  url: https://github.com/CombineCommunity/CombineExt
  from: 1.5.1

 ModernRIBs:
  url: https://github.com/DevYeom/ModernRIBs
  from: 1.0.0

 Swifter:
  url: https://github.com/httpswift/swifter
  from: 1.5.0

 Hammer:
  url: https://github.com/lyft/Hammer.git
  from: "0.13.0"

 Finance:
  path: Finance

 Platform:
  path: Platform

 Transport:
  path: Transport

 Profile:
  path: Profile

 CX:
  path: CX

options:
  tabWidth: 2 # tab 설정
  indentWidth: 2 # indent 설정

configs:
  Debug: debug
  Release: release
  UITest: debug

targets:
  MiniSuperApp:
    type: application # 타겟 타입
    platform: iOS # 타겟 플랫폼
    settings:
      base: 
        INFOPLIST_FILE: MiniSuperApp/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.moon.miniApp
        DEVELOPMENT_TEAM: "QL44HLLM22" 
    scheme:
      testTargets:
        - MiniSuperAppUITests
      gatherCoverageData: true       
    sources:
      - path: MiniSuperApp
    dependencies:
      - package: CombineExt
      - package: ModernRIBs
      - package: Finance
        product: AddPaymentMethod
      - package: Finance
        product: AddPaymentMethodImpl
      - package: Finance
        product: Topup
      - package: Finance
        product: TopupImpl
      - package: Finance
        product: FinanceHome
      - package: Platform
        product: RIBsUtil
      - package: Platform
        product: SuperUI
      - package: Transport
        product: TransportHome
      - package: Profile
        product: ProfileHome
      - package: CX
        product: AppHome
      - package: Transport
        product: TransportHomeImpl
      - package: Platform
        product: Network
      - package: Platform
        product: NetworkImp

  MiniSuperAppUITests:
    type: bundle.ui-testing
    platform: iOS
    settings:
      base:
        INFOPLIST_FILE: MiniSuperApp/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.moon.miniApp
        DEVELOPMENT_TEAM: "QL44HLLM22"
    scheme:
      testTargets:
        - MiniSuperAppUITests
      gatherCoverageData: true
    sources:
      - path: MiniSuperAppUITests
    dependencies:
      - package: Platform
        product: PlatformTestSupport
        link: true
      - target: MiniSuperApp
  AddPaymentMethodIntegrationTests:
    type: bundle.unit-test
    platform: iOS
    settings:
      base:
        INFOPLIST_FILE: MiniSuperApp/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.moon.miniApp
        DEVELOPMENT_TEAM: "QL44HLLM22"
    scheme:
      testTargets:
        - AddPaymentMethodIntegrationTests
      gatherCoverageData: true
    sources:
      - path: AddPaymentMethodIntegrationTests
    dependencies:
      - package: Platform
        product: PlatformTestSupport
      - package: Finance
        product: FinanceRepository
      - package: Finance
        product: AddPaymentMethod
      - package: Finance
        product: AddPaymentMethodImpl
      - package: Finance
        product: FinanceRepositoryTestSupport
      - package: Finance
        product: AddPaymentMethodTestSupport
