name: MiniSuperApp
packages: 
 CombineExt:
  url: https://github.com/CombineCommunity/CombineExt
  from: 1.5.1

 ModernRIBs:
  url: https://github.com/DevYeom/ModernRIBs
  from: 1.0.0

 Swifter:
  url: https://github.com/httpswift/swifter
  from: 1.5.0

 Hammer:
  url: https://github.com/lyft/Hammer.git
  from: "0.13.0"

 Finance:
  path: Finance

 Platform:
  path: Platform

 Transport:
  path: Transport

 Profile:
  path: Profile

 CX:
  path: CX

options:
  tabWidth: 2 # tab 설정
  indentWidth: 2 # indent 설정
  
targets:
  MiniSuperApp:
    type: application # 타겟 타입
    platform: iOS # 타겟 플랫폼
    settings:
     base: 
      INFOPLIST_FILE: MiniSuperApp/Info.plist
      PRODUCT_BUNDLE_IDENTIFIER: com.moon.miniApp
     configs:
       Debug:
        DevelopmentTeam: QL44HLLM22
    scheme:
      testTargets:
        - MiniSuperAppUITests
    sources: # 소스들 추가
      - path: MiniSuperApp
    dependencies:
      - package: CombineExt
      - package: ModernRIBs
      - package: Finance
        product: AddPaymentMethod
      - package: Finance
        product: AddPaymentMethodImpl
      - package: Finance
        product: Topup
      - package: Finance
        product: TopupImpl
      - package: Finance
        product: FinanceHome
      - package: Platform
        product: RIBsUtil
      - package: Platform
        product: SuperUI
      - package: Transport
        product: TransportHome
      - package: Profile
        product: ProfileHome
      - package: CX
        product: AppHome
      - package: Transport
        product: TransportHomeImpl
      - package: Platform
        product: Network
      - package: Platform
        product: NetworkImp

  MiniSuperAppUITests:
    type: bundle.ui-testing
    platform: iOS
    settings:
     base:
      INFOPLIST_FILE: MiniSuperApp/Info.plist
      PRODUCT_BUNDLE_IDENTIFIER: com.moon.miniApp
     configs:
       Debug:
         DEVELOPMENT_TEAM: "QL44HLLM22"
    scheme:
      testTargets:
        - MiniSuperAppUITests
      gatherCoverageData: true
    sources: # 소스들 추가
      - path: MiniSuperAppUITests
    dependencies:
      - package: Platform
        product: PlatformTestSupport
        link: true
      - target: MiniSuperApp
  TestHost:
    type: application # 타겟 타입
    platform: iOS # 타겟 플랫폼
    settings:
     base: 
      INFOPLIST_FILE: TestHost/Info.plist
      PRODUCT_BUNDLE_IDENTIFIER: com.moon.testhost
     configs:
       Debug:
        DevelopmentTeam: QL44HLLM22
    sources: # 소스들 추가
      - path: TestHost
    dependencies:
      - package: Finance
        product: AddPaymentMethodImpl
      - package: Hammer


  AddPaymentMethodIntegrationTests:
    type: bundle.unit-test
    platform: iOS
    settings:
      TEST_HOST: TestHost
      PRODUCT_BUNDLE_IDENTIFIER: com.moon.testhost
    sources: AddPaymentMethodIntegrationTests

schemes:
  SuperMiniApp:
    build:
      targets:
        MiniSuperApp: all
        MiniSuperAppUITests: [build, test]
        AddPaymentMethodIntegrationTests: all
