name: MiniSuperApp
packages: 
 CombineExt:
  url: https://github.com/CombineCommunity/CombineExt
  from: 1.5.1

 ModernRIBs:
  url: https://github.com/DevYeom/ModernRIBs
  from: 1.0.0

 Finance:
  path: Finance

 Platform:
  path: Platform

 Transport:
  path: Transport

 Profile:
  path: Profile

 CX:
  path: CX

targets:
  MiniSuperApp:
    type: application # 타겟 타입
    platform: iOS # 타겟 플랫폼
    settings:
     base: 
      INFOPLIST_FILE: MiniSuperApp/Info.plist
      PRODUCT_BUNDLE_IDENTIFIER: com.moon.miniApp
     configs:
       Debug:
         DEVELOPMENT_TEAM: "QL44HLLM22"

    sources: # 소스들 추가
      - path: MiniSuperApp
    dependencies:
      - package: CombineExt
      - package: ModernRIBs
      - package: Finance
        product: AddPaymentMethod
      - package: Finance
        product: Topup
      - package: Finance
        product: FinanceHome
      - package: Platform
        product: RIBsUtil
      - package: Platform
        product: SuperUI
      - package: Transport
        product: TransportHome
      - package: Profile
        product: ProfileHome
      - package: CX
        product: AppHome

schemes:
  SuperMiniApp:
    build:
      targets:
        MiniSuperApp: all
    run:
